### ISSUE TITLE
上传到git本地仓库的时候连接不到我的克隆地址是怎么回事

### ISSUE THREAD

**Issue by lulu7795** [OpenHUTB/neuro#101]
![Uploading 屏幕截图 2024-03-22 121949.png…]()

**Comment by donghaiwang** [comment]
![image](https://github.com/OpenHUTB/neuro/assets/7724320/8ad71f92-b3e6-4ef4-81fd-695725b64aa4)
这个截图看不到。

**Comment by QJWSH** [comment]
大概率是网络问题

**Comment by Qqqqhl** [comment]
网不好
