### ISSUE TITLE
不懂就问，这个星期五上课的时候需要汇报什么内容？

### ISSUE THREAD

**Issue by baifeng66** [OpenHUTB/neuro#124]
汇报一下自己做的部分，但是具体需要讲些什么？ 
@donghaiwang

**Comment by donghaiwang** [comment]
> 汇报一下自己做的部分，但是具体需要讲些什么？ 
> @donghaiwang 
> 

Git协作开发碰到的问题和解决办法+所负责章节的内容的理解

**Comment by baifeng66** [comment]
ok 了解
