### ISSUE TITLE
原始链接在页面中显示出来了

### ISSUE THREAD

**Issue by donghaiwang** [OpenHUTB/neuro#13]
可以参考下别人的写法再提交一个pull request 来修复这个问题 @kkkkkke6 

![image](https://github.com/OpenHUTB/neuro/assets/7724320/9d6e6028-fc7f-4564-9c41-a0b18010edc1)

**Comment by QJWSH** [comment]
*[name](URL)，eg：[李四](https://....)*

**Comment by QJWSH** [comment]
\[name\]\(URL\)，eg：\[李四\]\(https://....\)

**Comment by donghaiwang** [comment]
![image](https://github.com/OpenHUTB/neuro/assets/7724320/f24626cb-7335-4195-9ba9-54d7d2ce2b55)
@peng2023-ai
