### ISSUE TITLE
git push失败怎么搞捏？

### ISSUE THREAD

**Issue by forbruce** [OpenHUTB/neuro#145]
![image](https://github.com/OpenHUTB/neuro/assets/103575736/f18835fa-cb6f-49cb-bd8a-554b3011593e)

**Comment by feicheng0909** [comment]
你这个应该是网络超时了，开启网络代理应该可以解决！

**Comment by forbruce** [comment]
> 你这个应该是网络超时了，开启网络代理应该可以解决！

原来如此，照做果然成功了！ 感谢~

**Comment by Qqqqhl** [comment]
> 你这个应该是网络超时了，开启网络代理应该可以解决！

666
