### ISSUE TITLE
请问这个冲突怎么解决，突然就出现了

### ISSUE THREAD

**Issue by OopsCCK** [OpenHUTB/neuro#207]
![68f2c6a1003358185093c860102348d3](https://github.com/OpenHUTB/neuro/assets/85062312/a63d4c7e-f16a-4531-ae0e-1500a4fe8e28)

**Comment by donghaiwang** [comment]
应该是自己的修改和主分支上的修改冲突了，合并主分支的时候会出现冲突，需要解决，在这个小乌龟工具中就是需要手动右键选择左边还是右边是你需要保留的内容，最后退出时标记为已解决冲突，才可以继续提交。
