### ISSUE TITLE
请问如何解决push时超出文件大小限制的报错

### ISSUE THREAD

**Issue by OopsCCK** [OpenHUTB/neuro#212]
![ced2eaba90067d518b2fd98e820d46b1](https://github.com/OpenHUTB/neuro/assets/85062312/e34ab648-341c-4dcb-b317-3a5cfb6e9cbf)

试了网上的解决办法不管用，之前push都没问题，现在怎么都push不上去了

**Comment by donghaiwang** [comment]
不能把编译生成的pdf上传，这个很大，git仓库只管理代码，neuro.pdf是生成的结果，可以由tex文件编译得到。
