### ISSUE TITLE
和中英文对照表的翻译不一致

### ISSUE THREAD

**Issue by donghaiwang** [OpenHUTB/neuro#296]
第38章 248 行明显有问题，`\textit{$\alpha$-氨基-3-羟基-5-甲基-4-异恶唑丙酸}` 和中英文对照表的翻译不一致，如果觉得中英文对照表有问题就需要修改中英文对照表。

@huduo0   @yanshuqiiii

**Comment by huduo0** [comment]
已修改中英文对照表
