### ISSUE TITLE
git push 显示 neuro.pdf>100M 求解决！！！

### ISSUE THREAD

**Issue by forbruce** [OpenHUTB/neuro#312]
问题是这样： 
git add chap35/chap35.tex
正常运行
git commit -m "修改chap35.tex"
正常运行
git push
就开始报错，似乎是因为git push时，把neuro.pdf也算上了，我也rm 清理过，但是依然没有作用。
似乎对于neuro的追踪是一直在的，这个要怎么解决呢？
我之前也提交过，成功了，但是后来的每次git push 一直报这个错误

**Comment by Qqqqhl** [comment]
跟你一样

**Comment by OopsCCK** [comment]
我也有过这个问题，可以重新clone一遍，然后把之前修改的内容贴到新clone的文件里
