### ISSUE TITLE
作业流程是按这个步骤吗

### ISSUE THREAD

**Issue by BookName123** [OpenHUTB/neuro#65]
1.先从自己的仓库里复制从主仓库fork的项目url
2.git clone  “自己仓库neuro的url”到本地文件夹里
3.选择自己的chap.tex加一个空格或回车，用textStudio编译
4.git diff
5.git  add chap01/chap.tex
6.git commit "具体描述"
7.git push
8.新建 pull request

**Comment by donghaiwang** [comment]
流程是对的，修改完自己的tex文件后，是编译neuro.tex，会包含所有的tex文件进行编译，能成功生成neuro.pdf表示成功。

**Comment by zhanghan217** [comment]
一定是clone自己仓库的neuro吗

**Comment by donghaiwang** [comment]
> 一定是clone自己仓库的neuro吗

是的，就是clone fork后的那个仓库，因为克隆湖工商组织的仓库没有直接push的权限，需要从自己的仓库向湖工商仓库提交pull request
