### ISSUE TITLE
编译报错

### ISSUE THREAD

**Issue by iiarachel** [OpenHUTB/neuro#66]
<img width="1280" alt="微信图片_20240315224621" src="https://github.com/OpenHUTB/neuro/assets/63531784/f2a861ed-d39c-4a6e-b070-b5821b3fdd4f">
老师，添加换行之后，编译报错，没有改别的地方，咋解决呀

**Comment by donghaiwang** [comment]
不是编译chap19.tex，而是编译neuro.tex。
另外先要啥都不改保证能编译通过在修改源文件。
