### ISSUE TITLE
编译pdf报错

### ISSUE THREAD

**Issue by feicheng0909** [OpenHUTB/neuro#72]
![微信图片_20240317233636](https://github.com/OpenHUTB/neuro/assets/162286207/ba974c81-74cf-49d3-82f7-d2462706f794)

**Comment by BookName123** [comment]
![f84d463c86fcab9b49fe74444de4fbc](https://github.com/OpenHUTB/neuro/assets/146154576/6d802198-6efc-4011-9e46-e79337e5b59c)
把除了neueo.tex的其他带neueo的文件都删了再编译，应该就没问题了
