### ISSUE TITLE
编译错误

### ISSUE THREAD

**Issue by feicheng0909** [OpenHUTB/neuro#73]
<img width="921" alt="微信图片_20240317233923" src="https://github.com/OpenHUTB/neuro/assets/162286207/6e12bc94-3e2c-49ae-8f0e-2dc6097f4179">
不知道哪里错了

**Comment by BookName123** [comment]
![解决方案1](https://github.com/OpenHUTB/neuro/assets/146154576/00db1d75-13ce-49c6-99da-f1eefd75a35e)
看一下是不是这里没改过来

**Comment by forbruce** [comment]
![1](https://github.com/OpenHUTB/neuro/assets/103575736/a71ce43b-420a-47ac-aa89-774d11820811)
![2](https://github.com/OpenHUTB/neuro/assets/103575736/ac72cf1f-427a-4ece-ab79-6bf7bd3c9066)
![3](https://github.com/OpenHUTB/neuro/assets/103575736/3ad719aa-8512-4fd0-8c43-760dafd1f1c4)
这些地方修改一下，应该就ok了
