### ISSUE TITLE
我是按照参考文档做的，用的SSH的秘钥，但是在要下载到本地仓库的时候老是报错

### ISSUE THREAD

**Issue by peng2023-ai** [OpenHUTB/neuro#83]
No supported authentication methods available (server sent:
publickey)

**Comment by donghaiwang** [comment]
试下这个 [解决办法](https://blog.csdn.net/Jeffxu_lib/article/details/112259246) 。

**Comment by peng2023-ai** [comment]
git.exe clone --progress -v "git@github.com:OpenHUTB/neuro.git" "D:\git\library\neuro"
Cloning into 'D:\git\library\neuro'...
/usr/bin/bash: git@github.com: No such file or directory
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
git did not exit cleanly (exit code 128) (282 ms @ 2024/3/20 10:26:12)
两种解决方案都尝试过了，还是会报错

**Comment by donghaiwang** [comment]
换成HTTPS的链接试试
